apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-app
  labels:
    app: payment-app
spec:
  selector:
    matchLabels:
      app: payment-app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s